config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  devise_scope :user do
    get "/users/cancel" => "users/registrations#cancel", as: :cancel_user_registration
    get "/users/sign_up" => "users/registrations#new", as: :new_user_registration
    get "/users/edit" => "users/registrations#edit", as: :edit_user_registration
    post "/users" => "users/registrations#create", as: :user_registration
    patch "/users" => "users/registrations#update", as: ''
    put "/users" => "users/registrations#update", as: ''
    delete "/users" => "users/registrations#destroy", as: ''
  end

  resources :seasons do
    resources :suggestions, only: [:new, :edit, :create, :update, :destroy], controller: "seasons/suggestions" do
      post :pick, on: :collection, as: :pick_in
    end
  end
  resources :movies, only: [:index, :show, :destroy] do
    get :search, on: :collection
  end

  root 'home#index'
end

app/models/season.rb
# == Schema Information
#
# Table name: seasons
#
#  id         :uuid             not null, primary key
#  god_mode   :boolean          default(FALSE)
#  name       :string
#  status     :integer          default("upcoming")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Season < ApplicationRecord
  MAX_SUGGESTIONS_PER_USER = 10

  enum status: { ongoing: 1, upcoming: 10, ended: 20 }

  has_many :suggestions, dependent: :destroy
  has_many :users, -> { distinct }, through: :suggestions

  validates :name, :status, presence: true

  scope :ordered, -> { order(status: :asc, created_at: :desc) }

  def self.current
    ongoing.first
  end

  def to_s
    name
  end

  def pick_suggestion!
    picked_suggestion = suggestions.not_picked.order('RANDOM()').first
    picked_suggestion.update(picked_at: Time.zone.now) if picked_suggestion.present?
  end
end

app/models/season/suggestion.rb
# == Schema Information
#
# Table name: season_suggestions
#
#  id         :uuid             not null, primary key
#  picked_at  :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  movie_id   :uuid             not null
#  season_id  :uuid             not null
#  user_id    :uuid             not null
#
# Indexes
#
#  index_season_suggestions_on_movie_id   (movie_id)
#  index_season_suggestions_on_season_id  (season_id)
#  index_season_suggestions_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (movie_id => movies.id)
#  fk_rails_...  (season_id => seasons.id)
#  fk_rails_...  (user_id => users.id)
#
class Season::Suggestion < ApplicationRecord
  attr_accessor :movie_tmdb_identifier

  belongs_to :season
  belongs_to :user
  belongs_to :movie

  validates :movie_id, uniqueness: true
  validate :must_respect_max_season_suggestions_per_user, on: :create

  before_validation :find_or_create_movie_from_tmdb, on: :create, if: :movie_tmdb_identifier

  scope :not_picked, -> { where(picked_at: nil) }
  scope :picked, -> { where.not(picked_at: nil) }

  private

  def find_or_create_movie_from_tmdb
    result_movie = Movie.find_or_create_from_tmdb(movie_tmdb_identifier)
    self.movie_id = result_movie.id if result_movie.present?
  end

  def must_respect_max_season_suggestions_per_user
    return if season.god_mode?
    errors.add(:base, :max_suggestions_reached) unless season.suggestions.where(user_id: user_id).count < Season::MAX_SUGGESTIONS_PER_USER
  end
end

app/controllers/seasons/suggestions_controller.rb
class Seasons::SuggestionsController < ApplicationController
  before_action :load_season
  before_action :load_suggestion, only: [:edit, :update, :destroy]

  def pick
    @season.pick_suggestion!
    redirect_back(fallback_location: @season)
  end

  def new
    @suggestion = @season.suggestions.new
    breadcrumb
    add_breadcrumb t('buttons.add')
  end

  def create
    @suggestion = @season.suggestions.new(suggestion_params)
    if @suggestion.save
      redirect_to @season, notice: t('notices.successfully_created', model: Season::Suggestion.model_name.human)
    else
      breadcrumb
      add_breadcrumb t('buttons.add')
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    breadcrumb
    add_breadcrumb t('buttons.edit')
  end

  def update
    @suggestion.update(suggestion_params)
    redirect_to @season, notice: t('notices.successfully_updated', model: Season::Suggestion.model_name.human)
  end

  def destroy
    @suggestion.destroy
    redirect_to @season, notice: t('notices.successfully_destroyed', model: Season::Suggestion.model_name.human)
  end

  protected

  def breadcrumb
    super
    add_breadcrumb Season.model_name.human(count: 2), seasons_path
    add_breadcrumb @season, @season
    add_breadcrumb Season::Suggestion.model_name.human(count: 2)
    add_breadcrumb @suggestion if @suggestion&.persisted?
  end

  private

  def suggestion_params
    params.require(:season_suggestion).permit(:movie_tmdb_identifier, :picked_at).merge(
      user_id: current_user.id,
      season_id: @season.id
    )
  end

  def load_season
    @season = Season.find(params[:season_id])
  end

  def load_suggestion
    @suggestion = @season.suggestions.find_by!(user_id: current_user.id, id: params[:id])
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :load_season, only: [:show, :edit, :update, :destroy]

  def index
    @seasons = Season.ordered
    breadcrumb
  end

  def show
    @user_suggestions = @season.suggestions.where(user_id: current_user.id).order(:created_at)
    @picked_suggestions = @season.suggestions.picked.order(picked_at: :desc)
    @remaining_suggestions = @season.suggestions.not_picked
    @remaining_user_suggestions = @user_suggestions.not_picked
    @last_picked_suggestion = @picked_suggestions.first
    breadcrumb
  end

  def new
    @season = Season.new
    breadcrumb
    add_breadcrumb t('buttons.add')
  end

  def edit
    breadcrumb
    add_breadcrumb t('buttons.edit')
  end

  def create
    @season = Season.new(season_params)
    if @season.save
      redirect_to @season, notice: t('notices.successfully_created', model: @season.to_s)
    else
      breadcrumb
      add_breadcrumb t('buttons.add')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @season.update(season_params)
      redirect_to @season, notice: t('notices.successfully_updated', model: @season.to_s)
    else
      breadcrumb
      add_breadcrumb t('buttons.edit')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @season.destroy
    redirect_to seasons_url, notice: t('notices.successfully_destroyed', model: @season.to_s)
  end

  protected

  def breadcrumb
    super
    add_breadcrumb Season.model_name.human(count: 2), seasons_path
    add_breadcrumb @season, @season if @season&.persisted?
  end

  private

  def season_params
    params.require(:season).permit(:name, :status, :god_mode)
  end

  def load_season
    @season = Season.find(params[:id])
  end
end

app/views/seasons/_form.html.erb
<%= simple_form_for season do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="row">
    <div class="col-md-4">
      <%= f.input :name %>
      <%= f.input :status, collection: Season.statuses.keys.map { |status| [t("activerecord.attributes.season.statuses.#{status}"), status] }, include_blank: false %>
      <%= f.input :god_mode %>
    </div>
  </div>
  <%= f.submit t('buttons.save'), class: "btn btn-primary" %>
<% end %>

app/views/seasons/_season.html.erb
<div class="card w-100 h-100">
  <div class="card-body">
    <div class="float-end">
      <% if season.upcoming? %>
        <span class="badge bg-secondary"><%= t("activerecord.attributes.season.statuses.upcoming") %></span>
      <% end %>
      <% if season.ongoing? %>
        <span class="badge bg-primary"><%= t("activerecord.attributes.season.statuses.ongoing") %></span>
      <% end %>
      <% if season.ended? %>
        <span class="badge bg-success"><%= t("activerecord.attributes.season.statuses.ended") %></span>
      <% end %>
    </div>
    <h5 class="card-title">
      <%= season %>
    </h5>
    <p class="card-text"><%= season.suggestions.size %> <%= Movie.model_name.human(count: 2).downcase %></p>
    <div class="card-actions">
      <%= link_to t("buttons.see"), season, class: "btn btn-sm btn-primary" %>
      <%= link_to t("buttons.edit"), [:edit, season], class: "btn btn-sm btn-warning" %>
      <%= link_to t("buttons.destroy"), season, method: :delete, data: { confirm: t('alerts.please_confirm') }, class: "btn btn-sm btn-danger" %>
    </div>
  </div>
</div>

app/views/seasons/edit.html.erb
<div class="container-fluid">
  <h1><%= @season %></h1>
  <%= render "form", season: @season %>
</div>

app/views/seasons/index.html.erb
<div class="container-fluid">
  <h1><%= Season.model_name.human(count: 2) %> (<%= @seasons.size %>)</h1>

  <div class="actions mb-4">
    <%= link_to t("buttons.add"), new_season_path, class: "btn btn-success" %>
  </div>

  <div class="row">
    <% @seasons.each do |season| %>
      <div class="col-md-3">
        <%= render "seasons/season", season: season %>
      </div>
    <% end %>
  </div>
</div>

app/views/seasons/new.html.erb
<div class="container-fluid">
  <h1><%= Season.model_name.human %></h1>
  <%= render "form", season: @season %>
</div>

app/views/seasons/show.html.erb
<div class="container-fluid">
  <h1><%= @season %></h1>

  <div class="actions mb-4">
    <%= link_to t("buttons.edit"), [:edit, @season], class: "btn btn-warning" %>
    <%= link_to t("buttons.destroy"), @season, method: :delete, data: { confirm: t('alerts.please_confirm') }, class: "btn btn-danger" %>
  </div>

  <hr>

  <% if @season.users.any? %>
    <h3><%= User.model_name.human(count: 2) %></h3>
    <ul>
      <% @season.users.each do |user| %>
        <%-
        user_suggestions_count = @season.suggestions.where(user_id: user.id).size
        user_remaining_suggestions_count = @season.suggestions.not_picked.where(user_id: user.id).size
        -%>
        <li>
          <%= user %> :
          <%= user_suggestions_count %> <%= Season::Suggestion.model_name.human(count: user_suggestions_count).downcase %>
          (non tirées : <%= user_remaining_suggestions_count %>)
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if @season.upcoming? %>
    <h2><%= Season::Suggestion.model_name.human(count: 2) %> (<%= @season.suggestions.count %>)</h2>
    <div class="actions mb-4">
      <% if current_user.can_make_suggestions?(@season) %>
        <%= link_to t("seasons.add_suggestion"), new_season_suggestion_path(@season), class: "btn btn-success" %>
      <% end %>
    </div>
    <div class="row mb-4">
      <% @user_suggestions.each do |suggestion| %>
        <div class="col-md-2">
          <%= render "seasons/suggestions/suggestion", suggestion: suggestion %>
        </div>
      <% end %>
    </div>
  <% else %>
    <h2><%= Movie.model_name.human(count: 2) %></h2>

    <% if @remaining_suggestions.size > 0 %>
      <div class="actions mb-4">
        <p><%= t("seasons.remaining_suggestions") %> : <%= @remaining_suggestions.size %></p>
        <%= link_to t("seasons.pick_suggestion"), pick_in_season_suggestions_path(@season), method: :post, data: { confirm: t("alerts.please_confirm") }, class: "btn btn-success" %>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-3">
        <%= render "seasons/suggestions/suggestion", suggestion: @last_picked_suggestion unless @last_picked_suggestion.nil? %>
      </div>
      <div class="col-md-9">
        <div class="row">
        <% @picked_suggestions.each_with_index do |suggestion, index| %>
          <% next if index.zero? %>
          <div class="col-md-2">
            <%= render "seasons/suggestions/suggestion", suggestion: suggestion %>
          </div>
        <% end %>
        </div>
      </div>
    </div>

    <% if @remaining_user_suggestions.any? %>
      <hr class="my-4">
      <h2><%= t('seasons.your_remaining_suggestions') %></h2>
      <button class="btn btn-primary"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#userSuggestionsCollapse"
              aria-expanded="false"
              aria-controls="userSuggestionsCollapse">
        Afficher / Cacher
      </button>
      <div class="collapse" id="userSuggestionsCollapse">
        <div class="row mt-3 mb-4">
          <% @remaining_user_suggestions.each do |suggestion| %>
            <div class="col-md-2">
              <%= render "seasons/suggestions/suggestion", suggestion: suggestion, hide_suggested_by: true %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>