config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  devise_scope :user do
    get "/users/cancel" => "users/registrations#cancel", as: :cancel_user_registration
    get "/users/sign_up" => "users/registrations#new", as: :new_user_registration
    get "/users/edit" => "users/registrations#edit", as: :edit_user_registration
    post "/users" => "users/registrations#create", as: :user_registration
    patch "/users" => "users/registrations#update", as: ''
    put "/users" => "users/registrations#update", as: ''
    delete "/users" => "users/registrations#destroy", as: ''
  end

  resources :seasons do
    resources :suggestions, only: [:new, :edit, :create, :update, :destroy], controller: "seasons/suggestions" do
      post :pick, on: :collection, as: :pick_in
    end
  end
  resources :movies, only: [:index, :show, :destroy] do
    get :search, on: :collection
  end

  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chapeau Petit Rex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/png" href="/favicon.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", defer: true %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <%= link_to "Chapeau Petit Rex", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to t("home"), root_path, class: class_names("nav-link", { "active": (controller_name == "home") }) %>
              </li>
              <li class="nav-item">
                <%= link_to Season.model_name.human(count: 2), seasons_path, class: class_names("nav-link", { "active": (controller_name == "seasons") }) %>
              </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
              <% if user_signed_in? %>
                <li class="nav-item dropdown">
                  <%= link_to current_user, "#", class: "nav-link dropdown-toggle", role: "button", data: { "bs-toggle": "dropdown" }, aria: { expanded: false } %>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li><%= link_to t("nav.account"), edit_user_registration_path, class: "dropdown-item" %></li>
                    <li><%= link_to t("nav.sign_out"), destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                  </ul>
                </li>
              <% else %>
                <li class="nav-item dropdown">
                  <%= link_to t('nav.not_connected'), "#", class: "nav-link dropdown-toggle", role: "button", data: { "bs-toggle": "dropdown" }, aria: { expanded: false } %>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li><%= link_to t("devise.shared.links.sign_in"), new_user_session_path, class: "dropdown-item" %></li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= render_breadcrumbs builder: BootstrapBreadcrumbsBuilder if @breadcrumbs_on_rails.present? && @breadcrumbs_on_rails.length > 1 %>
    <main class="my-3">
      <% if notice.present? %>
        <div class="container">
          <div class="alert alert-primary alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="container">
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= alert %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>